disabled_rules: # rule identifiers turned on by default to exclude from running
  - line_length
  - identifier_name
  - trailing_whitespace
  - trailing_comma
  - function_parameter_count
excluded:
  - Pods