name: Run test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

jobs:
  test:
    name: Build and Run test
    runs-on: macos-14

    steps:
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: bundle-ruby-${{ runner.os }}-${{ env.RUBY_VERSION }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-        
      - name: Set up build
        run: |
          make setup
      - name: Disable macro validation
        run: |
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Run test
        run: |
          bundle exec fastlane test
