name: Run test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

jobs:
  test:
    name: Build and Run test
    runs-on: macos-14

    steps:
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      # - name: Run test
      #   id: run_tests
      #   run: |
      #     bundle install
      #     {
      #       echo 'test-result<<EOF'
      #       bundle exec fastlane docs
      #       echo EOF
      #     } >> "$GITHUB_OUTPUT"
      # - name: Output
      #   run: |
      #     echo "# Test output"
      #     RESULT=`##${{ steps.run_tests.outputs.test-result }}##`
      #     echo "Hello world: $(RESULT)"
      - name: Run test
        id: run_tests
        run: |
          bundle install
          bundle exec fastlane docs > /tmp/test-result.log
      - name: Output
        run: |
          OUTPUT=`cat /tmp/test-result.log | grep -E '\[action\]'`
          echo "## Test coverage report"
          echo "${OUTPUT}"
    